---
# Form running gradle locally
server:
  port: 8585
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:file:./db/h2_db
    driverClassName: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    databse-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: true
